Repository josephcyang4459/josephcyang4459.github.io, pull requests merged in 2024-01, with the labels that each got.

#25 critical fix for contact form. action wasn't not set.
  index.html
Labels: bug

#26 20 do links overlay
  css/main.css
  images/link-icons/email-icon-hover.png
  images/link-icons/email-icon.png
  images/link-icons/github-icon-hover.png
  images/link-icons/github-icon.png
  images/link-icons/itchio-icon-hover.png
  images/link-icons/itchio-icon.png
  images/link-icons/link-arrow-hover.png
  images/link-icons/link-arrow.png
  images/link-icons/linkedin-icon-hover.png
  images/link-icons/linkedin-icon.png
  index.html
Labels: bug, enhancement

#27 Development
  css/main.css
  images/about-image.png
  images/link-icons/email-icon-hover.png
  images/link-icons/email-icon.png
  images/link-icons/github-icon-hover.png
  images/link-icons/github-icon.png
  images/link-icons/itchio-icon-hover.png
  images/link-icons/itchio-icon.png
  images/link-icons/link-arrow-hover.png
  images/link-icons/link-arrow.png
  images/link-icons/linkedin-icon-hover.png
  images/link-icons/linkedin-icon.png
  images/preview-image.PNG
  index.html
Labels: documentation, enhancement

#28 hot fix on the portrait image not showing.
  index.html
Labels: bug

#31 Added cred footer
  css/main.css
  index.html
Labels: documentation, enhancement

#32 updated github profile name change.
  index.html
Labels: bug

#33 updated resume
  assets/Resume - Joseph Yang.pdf
Labels: enhancement
